language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: sDGjyW+yFu2dqT/7LeT+lqJB+7AFyHcjr6mqepANM3qY0E3itd6iXDN9gWpINCj++TnvchkHOhwh1JhFhKlSMpK49fBou9ibRnuAJCKhwmJ+fcdWPrII/cYtlf8a6+X3MCT49cogUjJ82FMRJi2OZOlu74BvB8ewsKJGyImlG0N4djFqN7wx0uxJC1p7SQJMo5xe7Tq56zCEa0w80GYheubYJPmKLxCtUtiP5LpH8Hgimbct6Bha9aNfQSfzT94DYvsgvff7nJ+lt8v2t57lgTlR/byTf3VSuu3dX2jSu9IN3mDWwTRxv+tIRGynkKZ7lbH6hZ/4myfcDTJYl/4Up8eDynTGnzaEFPSdcB/VkvC9h6GAUSVgubQG8wVlVvcC2Kwc+tMiuLpS0clzCS3r+/b2F7CL/jPdyS3gzo6DHsdwuW7FhMICTGvBNisnV4/oAZUJ0vhWRBtgW7UbzgHsUlV5aOgQCi6RlA7nZi2m/3gjBK+eC2+ojYSVw5/Ka16Y5eCpBKJ94X7GtVMjTWrV064BU9ypzNOoYRrniOXksNYuX8R8DbHwMVcS/ar3rCKYuQI8WXH/QuS5vf/Kuz97YZMRDMOKolTwHGXN8nfugsY/VeK1nx+IEqyi2J+sEPDGxJ82aY1M7sAbeB/ovBmi8lYBHcezditsodglHwKhu+Q=
  - secure: tam5xw9bX9UTE8PYcuX50Uf0o58BJNlYU+O3E5W5zcs4OjblbtSV2u/zaDC7Ij6Y2jUmK/ZaVaDP5CfNEFpQo1ajXPAsk6qWjZ7kK380swocfbbiJy54pvowEfRw/tTwwuydo+CrrxNWdWaooBvtt15pLyrEzZWT+X3LCzsVYVxGUG7pVNd9B9XjyiArVkMT+X6bVx8v+dNLvx8tCi2RYDNGTklv+CMYpCYTDfAnvepK8+bVfzxecmWAy5cK4Tbhbx8yYNCEEnW+EKSRR908taBvhPbFpjcso/GMqUYqho9VtATYpftLbiffe5VMqSdgzUhmqxrtdjXkmlNK88tswgL4wTKL5SeeTwqW6yiSW7QJZdrAUtdkhyWXyd7E1apzP3yVDWTK1Iu5QsmSaMUgVsfAiFTBmhpSGBf2Rvl5HrtOZJgUq6XrmDEr4Zg5GjH5Q2yG3ipgMPRIoQvHRYIVQqyx/jwejz+VyMrTinU8TiByUm4AAvxkGeZ7poG9S99ayg1w1Q/pOcj86ABtMyH1wVbdY+x5bGPx4Zw7zN8M1mKcPhrw1+TdGjAr3t0uEWu6JDW64L513nf16XFDL/jao/JwwMbPSb3BgTx2CE5xDvc5QAwZmMsH2aJuST9GyOFhhjC9QDmhVecQJVe2UCY6hBI3Q/DmnT1Ho88bHb6bCTo=
install: "./gradlew assemble -PbintrayUser=${bintrayUser} -PbintrayKey=${bintrayKey}"
script: "./gradlew clean build :chinook-core:bintrayUpload -x fregeQuickCheck -PbintrayUser=${bintrayUser}
  -PbintrayKey=${bintrayKey}"
branches:
  only:
  - master
